// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftLine_TA.Models;

namespace SoftLine_TA.Server.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20231212115852_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SoftLine_TA.Models.Status", b =>
                {
                    b.Property<int>("Status_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Status_ID");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Status_ID = 1,
                            Status_name = "Создана"
                        },
                        new
                        {
                            Status_ID = 2,
                            Status_name = "В работе"
                        },
                        new
                        {
                            Status_ID = 3,
                            Status_name = "Завершена"
                        });
                });

            modelBuilder.Entity("SoftLine_TA.Models.Task", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Status_ID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("SoftLine_TA.Models.Task", b =>
                {
                    b.HasOne("SoftLine_TA.Models.Status", "Status")
                        .WithMany("Tasks")
                        .HasForeignKey("Status_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SoftLine_TA.Models.Status", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
